apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o infra/k8s/kompose-generated/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: coqui-tts
  name: coqui-tts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coqui-tts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o infra/k8s/kompose-generated/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/multi-container-app-default: "true"
        io.kompose.service: coqui-tts
    spec:
      containers:
        - args:
            - python3
            - TTS/server/server.py
            - --model_name
            - tts_models/multilingual/multi-dataset/xtts_v2
          env:
            - name: COQUI_TTS_MODEL
              value: tts_models/multilingual/multi-dataset/xtts_v2
          image: ghcr.io/coqui-ai/tts-cpu:latest
          livenessProbe:
            exec:
              command:
                - wget
                - -qO-
                - http://localhost:5002
            failureThreshold: 5
            periodSeconds: 20
            timeoutSeconds: 5
          name: coqui-tts
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
